
library(fars)

---
title: "fars Package Overview"
author: "L. Mitchell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fars Package Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Summary
The `fars` package contains data sets on fatal motor vehicle crashes in the 
United States for the years 2013, 2014, and 2015. The data come from the 
U.S. National Highway Traffic Safety Administration's Fatality Analysis 
Reporting System (FARS). The package also contains functions designed to make 
loading, summarizing, and plotting maps of the FARS data easier.

## Data

The FARS data for each of the years 2013, 2014, and 2015 are stored in separate 
bz2 compressed csv files located in the `data` directory:

- accident_2013.csv.bz2
- accident_2014.csv.bz2
- accident_2015.csv.bz2

## Functions

The `fars` package features five functions. 

- make_filename: Use this to generate the file name for a FARS data file 
based on the year.
- fars_read: Use this to read in a FARS data set using the file's name.
- fars_read_years: Use this to read in multiple FARS data sets and store 
them in a list.
- fars_summarize_years: Use this to calculate the number of accidents by 
month and year, and display the results.
- fars_map_state: Use this to plot a map of the accidents from a specific 
date and year.

## Examples

```{r, echo=FALSE, results='asis'}
library(fars)
#my_file <- make_filename(year=2013)
#print(my_file)

#my_data <- fars_read(filename="accident_2013.csv.bz2")
#knitr::kable(head(my_data, 10))

#my_list <- fars_read_years(years=2013:2015)
#print(names(my_list))
#knitr::kable(head(my_list[1], 10))
#knitr::kable(head(my_list[2], 10))
#knitr::kable(head(my_list[3], 10))

#print(fars_summarize_years(years=2013:2015))

#fars_map_state(state.num=1, year=2013)
```
